name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [18]  # Start with just Node 18 to debug
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Debug Environment
      run: |
        echo "Node version: $(node -v)"
        echo "NPM version: $(npm -v)"
        echo "Operating System: $(uname -a)"
        echo "Current directory: $(pwd)"
        ls -la
        
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm ci --verbose
        echo "Dependencies installed successfully"
        
    - name: Verify MongoDB
      run: |
        echo "Checking MongoDB connection..."
        echo "show dbs" | mongosh --quiet localhost:27017
        echo "MongoDB check completed"
        
    - name: List Test Files
      run: |
        echo "Test files in __tests__ directory:"
        ls -R __tests__/
        
    - name: Run tests with debugging
      env:
        MONGODB_URI: mongodb://localhost:27017/testDatabase
        NODE_ENV: test
        DEBUG: "test:*,mongodb:*"
        CI: true
      run: |
        echo "Starting tests..."
        npm test -- --verbose --detectOpenHandles --runInBand --forceExit
      
    - name: Debug test failures
      if: failure()
      run: |
        echo "=== Test Debug Information ==="
        echo "MongoDB Status:"
        ps aux | grep mongo
        echo "=== MongoDB Logs ==="
        mongosh --eval "db.adminCommand('getLog', 'global')"
        echo "=== Node Process Information ==="
        ps aux | grep node
        echo "=== Directory Structure ==="
        ls -R
