name: Node.js CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: test
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 30s
          --health-retries 10
    strategy:
      matrix:
        node-version: [18]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      env:
        MONGODB_URI: mongodb://localhost:27017/test
        NODE_ENV: test
        DEBUG: mongodb:*,mongoose:*
      run: |
        # Wait for MongoDB to be ready
        timeout 20 bash -c 'until mongo --eval "db.runCommand({ ping: 1 })" localhost:27017/test; do sleep 1; done'
        npm test -- --verbose --detectOpenHandles --forceExit --testTimeout=30000
