name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04  # Use specific Ubuntu version if necessary

    services:
      mongodb:
        image: mongo:5.0  # Changed to a different MongoDB version (mongo:5.0)
        ports:
          - 27017:27017
        networks:
          - mongodb_network  # Custom network for MongoDB
        options: >-
          --memory 4g  # Allocate more memory to MongoDB container
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 30s
          --health-retries 10
    networks:
      mongodb_network:
        driver: bridge  # Network configuration

    strategy:
      matrix:
        node-version: [14.x, 16.x]  # Running jobs for both Node.js 14.x and 16.x

    steps:
      - name: Check Docker version
        run: docker --version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Retry Docker Mongo container creation
        run: |
          for i in {1..3}; do
            docker create --name mongodb --label github_action --network github_network -p 27017:27017 --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'" --health-interval 10s --health-timeout 30s --health-retries 10 mongo:5.0 && break || echo "Retrying Docker Mongo container creation..."; sleep 10;
          done

      - name: Show MongoDB container logs
        run: docker logs mongodb
        continue-on-error: true

      - name: Wait for MongoDB to be ready
        run: |
          until docker exec mongodb mongo --eval "db.runCommand({ ping: 1 })"; do
            echo "Waiting for MongoDB..."
            sleep 5
          done

      - name: Run tests
        env:
          MONGODB_URI: mongodb://localhost:27017/testDatabase
        run: npm test
