name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4  # Use a specific stable version
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 10s  # Increased timeout
          --health-retries 10   # Increased retries to handle slow startups

    strategy:
      matrix:
        node-version: [14.x, 16.x]  # Running jobs for both Node.js 14.x and 16.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          MONGODB_URI: mongodb://localhost:27017/testDatabase
        run: npm test
