name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [18]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm ci
        
    - name: Run tests
      env:
        MONGODB_URI: mongodb://localhost:27017/testDatabase
        NODE_ENV: test
        DEBUG: mongodb:*,mongoose:*
      run: |
        npm test -- --verbose --detectOpenHandles --forceExit --testTimeout=30000
